before_deploy:
  - cat .bundle/config
  - ls -al
  - du -sh ./*
  - du -sh ./vendor/bundle/ruby/2.2.0/gems/* | grep M | sort
  - du -sh ./vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.6.2/*
deploy:
  provider: heroku
  api_key:
    secure: AYxRooIgCDiZThui5EBQsb2bUgH6gU9fO7iyihGFtH+TtwgLxUhZMwBugE7rwFrr1HXwVpI2scT353xPTdrJpGSLBPxKJe+9niQhE3MkYwe5lO90ppd1/Mw/L0I/31OiudZ12qSIQhKWBqyJ7qxkQPF94g90CyjmY8HbxRZFmvkj4KMM0WS4qyPehFfpyviI3Ijp8QqaLP+sJb8GBfUrHdjg63Pg4SucqOCDsSmL+n6fGq0dh2Kl7NuuHHTZDiBRXyb+QGbc4u5hT+XNCr79ykgIkL5lgy8iVBOvJxdsZdJC01NmBUVD0uz5+Q5h/KQq30WDVCNB1WdhpQ3zu+l0BLqQBf32hlSD5tvLxViwZmO/P/Gu2DzAG5B1pwmY9hfU1ybGf8Lefb7NVrO7lZyYggQG82qtULMV71qMNwV5yzOBIDhTTrBRutJMwcODpG6YA1p4UKaafSUWvqHe1tB38n+fDpu2ZE3eOoQ8AcxKgddftNk8F2aATBLNMXO8gbgW/vygHljeZhRo1KClrFxwFU6JrSTSf/3Wvhqfx0yvZPayH6n/rjh5osyxW7dYibF7jCNaZ1u4Q64ZvG2/VjeLnlZA7CVNAySHN7N5sqvsHYt6MyB6a8OK9RWR6n6Fxo/jW/WKC/mBo5IegX3Lnj0H+6d47O1lTu8Grg7Sk4w1yqQ=
  app: guarded-stream-7829
  on:
    repo: cotsog/ruby-sample
script: true
cache: bundler
bundler_args: --no-cache
